# Generated by Django 6.0 on 2026-01-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_journalentry_period_journalentry_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounts.accountingperiod', verbose_name='الفترة المحاسبية'),
        ),
    ]
