# Generated by Django 6.0 on 2025-12-22 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_financialentry_status_alter_user_role_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='account_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='status',
            field=models.CharField(default='بانتظار المراجعة', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('manager', 'Financial Manager'), ('data_entry', 'Data Entry')], max_length=20),
        ),
    ]
