# Generated by Django 6.0 on 2025-12-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invoiceitem_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='account_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='status',
            field=models.CharField(default='بانتظار المراجعة', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('manager', 'Financial Manager'), ('data_entry', 'Data Entry')], default='data_entry', max_length=20),
        ),
    ]
