# Generated by Django 6.0 on 2026-01-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_journalentry_delete_financialentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='entry_type',
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.journalentry')),
            ],
        ),
    ]
