# Generated by Django 6.0 on 2026-01-13 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_journalentry_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزام'), ('equity', 'حقوق ملكية'), ('income', 'إيراد'), ('expense', 'مصروف')], max_length=20, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.account', verbose_name='الحساب الأب')),
            ],
        ),
    ]
