# Generated by Django 6.0 on 2026-01-13 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentryline',
            name='account_name',
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دائن'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مدين'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.journalentry', verbose_name='القيد'),
        ),
    ]
