# Generated by Django 6.0 on 2026-01-14 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_journalentryline_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'permissions': [('view_general_ledger', 'يمكنه عرض دفتر الأستاذ'), ('view_trial_balance', 'يمكنه عرض ميزان المراجعة')]},
        ),
      
        migrations.AlterField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='الحساب'),
        ),
    ]
