# Generated by Django 6.0 on 2026-01-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_journalentry_options_remove_account_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(
                choices=[
                    ('asset', 'أصول'),
                    ('liability', 'خصوم'),
                      ('equity', 'حقوق ملكية'), 
                      ('revenue', 'إيرادات'), 
                      ('expense', 'مصروفات')
                      ],
                        max_length=20, 
                        verbose_name='نوع الحساب'
                        ),
        ),
    ]
