# Generated by Django 6.0 on 2026-01-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_account_is_active_alter_account_account_type'),
    ]

   