# Generated by Django 6.0 on 2026-01-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_account_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentryline',
            options={'permissions': [('view_general_ledger', 'Can view general ledger')]},
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
