# Generated by Django 6.0 on 2026-01-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_journalentryline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('access_general_ledger', 'الدخول إلى دفتر الأستاذ')]},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
    ]
