# Generated by Django 6.0 on 2026-01-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_options_alter_journalentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('manual', 'قيد يدوي'), ('invoice', 'فاتورة'), ('adjustment', 'قيد تسوية'), ('opening', 'قيد افتتاحي')], default='manual', max_length=20),
        ),
    ]
