# Generated by Django 6.0 on 2026-01-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_journalentry_entry_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('access_general_ledger', 'الدخول إلى دفتر الأستاذ'), ('view_trial_balance', 'Can view trial balance')]},
        ),
    ]
