# Generated by Django 6.0 on 2026-01-23 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'permissions': [('view_trial_balance', 'يمكنه عرض ميزان المراجعة')]},
        ),
    ]
