# Generated by Django 6.0 on 2026-01-23 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_journalentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مقفلة')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('close_accounting_period', 'يمكنه إقفال الفترات المحاسبية')],
            },
        ),
    ]
