# Generated by Django 6.0 on 2026-01-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_accountingperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['start_date'], 'permissions': [('close_accounting_period', 'يمكنه إقفال الفترات المحاسبية')]},
        ),

        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(verbose_name='تاريخ القيد'),
        ),
    ]
