# Generated by Django 6.0 on 2026-01-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_accountingperiod_options_invoice_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
    ]
