# Generated by Django 6.0 on 2026-02-04 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_invoice_period_journalentry_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.accountingperiod', verbose_name='الفترة المحاسبية'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounts.accountingperiod', verbose_name='الفترة المحاسبية'),
        ),
    ]
