# Generated by Django 6.0 on 2026-03-03 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_account_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-date']},
        ),
       
        migrations.AddField(
            model_name='exchangerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('old_syp', 'ليرة قديمة'), ('new_syp', 'ليرة جديدة'), ('usd', 'دولار')], default='old_syp', max_length=10, verbose_name='old_syp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السعر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='applied_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('old_syp', 'ليرة قديمة'), ('new_syp', 'ليرة جديدة'), ('usd', 'دولار')], default='old_syp', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='سعر الصرف'),
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='updated_at',
        ),
    ]
