# Generated by Django 6.0 on 2026-03-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency', 'date')},
        ),
    ]
