# Generated by Django 6.0 on 2026-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_exchangerate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
