# Generated by Django 6.0 on 2026-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_accounting_safety_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_total_positive',
        ),
        migrations.RemoveConstraint(
            model_name='journalentryline',
            name='debit_positive',
        ),
        migrations.RemoveConstraint(
            model_name='journalentryline',
            name='credit_positive',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[('old_syp', 'ليرة قديمة'), ('new_syp', 'ليرة جديدة'), ('usd', 'دولار')], default='old_syp', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
    ]
