# Generated by Django 6.0 on 2026-03-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_invoice_invoice_total_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_account', to='accounts.account')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_account', to='accounts.account')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_account', to='accounts.account')),
            ],
        ),
    ]
