# Generated by Django 6.0 on 2026-03-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_accountingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='applied_exchange_rate',
        ),
    ]
