# Generated by Django 6.0 on 2026-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_invoice_applied_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
