# Generated by Django 6.0 on 2026-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_invoice_original_amount_invoice_original_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
