# Generated by Django 6.0 on 2026-03-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_invoice_exchange_rate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('old_syp', 'ليرة قديمة'), ('new_syp', 'ليرة جديدة'), ('usd', 'دولار')], max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[('SYP_OLD', 'ليرة سورية قديمة'), ('SYP_NEW', 'ليرة سورية جديدة'), ('USD', 'دولار')], default='SYP_OLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
