# Generated by Django 6.0 on 2026-03-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_journalentry_original_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[('old_syp', 'ليرة سورية قديمة'), ('new_syp', 'ليرة سورية جديدة'), ('usd', 'دولار')], default='old_syp', max_length=10),
        ),
    ]
